version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8080:15672

  app:
    image: golang
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - rabbitmq