version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 8080:15672
    volumes:
        - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker/rabbitmq/log/:/var/log/rabbitmq/

  app:
    image: golang
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - rabbitmq

volumes:
  rabbitmq-volume: